import { ApiProperty } from '@nestjs/swagger';

class ImageDetails {
  @ApiProperty({
    description: 'Image URL',
    example: 'https://example.com/image1.png',
    type: String,
  })
  url: string;

  @ApiProperty({
    description: 'Prompt used to generate the image',
    example: 'A beautiful sunset over mountains',
    type: String,
  })
  prompt: string;

  @ApiProperty({
    description: 'Creation date of the image',
    example: '2025-05-02T12:34:56.789Z',
    type: Date,
  })
  createdAt: Date;
}

export class UserImageResponse {
  @ApiProperty({
    description: "Image URL's that generated by the user",
    example: [
      'https://example.com/image1.png',
      'https://example.com/image2.png',
    ],
    type: [String],
  })
  imageUrls: string[];

  @ApiProperty({
    description: 'Detailed information about each image',
    type: [ImageDetails],
  })
  images: ImageDetails[];

  @ApiProperty({
    description: 'The number of images generated by the user',
    example: 2,
    type: Number,
  })
  count: number;
}
