import { ApiProperty } from '@nestjs/swagger';

export class UserImageResponse {
  @ApiProperty({
    description: "Image URL's that generated by the user",
    example: [
      'https://example.com/image1.png',
      'https://example.com/image2.png',
    ],
    type: [String],
  })
  imageUrls: string[];

  @ApiProperty({
    description: 'The number of images generated by the user',
    example: 2,
    type: Number,
  })
  count: number;
}
